const CFG={u13:{name:'Under 13',rounds:6,folder:'u13',date:'17 October 2026'},championship:{name:'Championship',rounds:16,folder:'championship',date:'17–18 October 2026'},plate:{name:'Plate / Newbies Category',rounds:7,folder:'plate',date:'18 October 2026'}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const qs=k=>new URLSearchParams(location.search).get(k)||'';
function eventKey(){const q=qs('event');if(CFG[q])return q;const f=location.pathname.split('/').pop().toLowerCase();if(f==='championship.html')return'championship';if(f==='plate.html')return'plate';return'u13'}
const cfg=()=>CFG[eventKey()];
function normId(v){const m=String(v||'').toUpperCase().match(/(?:#|[A-Z])?\s*\d+/);return m?m[0].replace(/\s+/g,'').replace(/^#/,''):''}
function rawPath(path){return `https://raw.githubusercontent.com/prop4life/colombo-scrabble-fiesta-2026/production/${path}?v=${Date.now()}`}
async function loadJSON(path){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('missing');return r.json()}
async function publishedFiles(folder){try{const r=await fetch(`https://api.github.com/repos/prop4life/colombo-scrabble-fiesta-2026/contents/${folder}?ref=production&v=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error('list failed');const items=await r.json();return new Set((Array.isArray(items)?items:[]).map(x=>x.name))}catch{return null}}
async function renderCategory(){const ev=cfg(),key=eventKey();document.title=`${ev.name} · Colombo Scrabble Fiesta 2026`;document.querySelector('#eventTitle').textContent=ev.name;document.querySelector('#eventDate').textContent=ev.date;document.querySelector('#profiles').href=`players.html?event=${key}`;const files=await publishedFiles(ev.folder);let html='';for(let r=1;r<=ev.rounds;r++){const n=String(r).padStart(2,'0'),pn=`round-${n}-pairings.html`,sn=`round-${n}-standings.html`;let p=files?files.has(pn):false,s=files?files.has(sn):false;if(!files){const checks=await Promise.all([fetch(rawPath(`${ev.folder}/${pn}`),{cache:'no-store'}).then(x=>x.ok).catch(()=>false),fetch(rawPath(`${ev.folder}/${sn}`),{cache:'no-store'}).then(x=>x.ok).catch(()=>false)]);[p,s]=checks}html+=`<section class="round"><h3>Round ${r}</h3><div class="status">${p?`<a class="live" href="viewer.html?event=${key}&round=${r}&type=pairings">View Pairings</a>`:'<span>Pairings — Not Published</span>'}${s?`<a class="live" href="viewer.html?event=${key}&round=${r}&type=standings">View Standings</a>`:'<span>Standings — Not Published</span>'}</div></section>`}document.querySelector('#rounds').innerHTML=html}
async function playerData(){const k=eventKey(),raw=`https://raw.githubusercontent.com/prop4life/colombo-scrabble-fiesta-2026/production/data/${k}.json?v=${Date.now()}`;try{const r=await fetch(raw,{cache:'no-store'});if(r.ok)return await r.json()}catch{}try{return await loadJSON(`data/${k}.json`)}catch{return{players:{}}}}
function photoPath(id){return `photos/${eventKey()}/${encodeURIComponent(normId(id))}.jpg`}
async function loadPlayers(){const ev=cfg(),d=await playerData(),arr=Object.values(d.players||{}).sort((a,b)=>(a.rank??9999)-(b.rank??9999)||a.name.localeCompare(b.name));document.querySelector('#eventTitle').textContent=`${ev.name} Player Profiles`;document.querySelector('#back').href=`${eventKey()}.html`;document.querySelector('#players').innerHTML=arr.length?arr.map(p=>`<div class="round"><a class="player" href="player.html?event=${eventKey()}&id=${encodeURIComponent(p.id)}">${esc(p.name)}</a><div class="muted">${p.games?.length||0} game(s) · ${p.wins||0}-${p.losses||0}-${p.ties||0} · Spread ${(p.spread||0)>=0?'+':''}${p.spread||0}</div></div>`).join(''):'<div class="panel">No standings published yet.</div>'}
function initials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
async function loadProfile(){const ev=cfg(),id=normId(qs('id')),d=await playerData(),p=(d.players||{})[id];document.querySelector('#back').href=`players.html?event=${eventKey()}`;if(!p){document.querySelector('#profile').innerHTML='<div class="panel">Player profile not found yet.</div>';return}const games=p.games||[],scoredGames=games.filter(g=>Number.isFinite(Number(g.score))),avgScore=scoredGames.length?(scoredGames.reduce((sum,g)=>sum+Number(g.score),0)/scoredGames.length).toFixed(1):'—',h={};for(const g of games){const oid=normId(g.opponentId);if(!oid)continue;h[oid]??={id:oid,name:g.opponentName||oid,games:0,w:0,l:0,t:0,spread:0};const x=h[oid];x.games++;if(g.result==='W')x.w++;else if(g.result==='L')x.l++;else if(g.result==='T')x.t++;x.spread+=Number(g.spread||0)}const photo=photoPath(id);document.querySelector('#profile').innerHTML=`<div class="panel"><div class="profile-top"><div><img id="photo" class="profile-photo" src="${photo}?v=${Date.now()}" alt="${esc(p.name)}"><div id="avatar" class="avatar" style="display:none">${esc(initials(p.name))}</div></div><div><div class="eyebrow">${esc(ev.name)}</div><h1>${esc(p.name)}</h1><div class="muted">Player ID: ${esc(p.id)}</div><div class="stats"><div class="stat"><b>${games.length}</b>Games</div><div class="stat"><b>${p.wins||0}-${p.losses||0}-${p.ties||0}</b>W-L-T</div><div class="stat"><b>${(p.spread||0)>=0?'+':''}${p.spread||0}</b>Spread</div><div class="stat"><b>${avgScore}</b>Avg. Score</div><div class="stat"><b>${p.rank??'—'}</b>Rank</div></div></div></div></div><div class="panel"><h2>Game History</h2><div class="tablewrap"><table><tr><th>Round</th><th>Opponent</th><th>Score</th><th>Opp.</th><th>Result</th><th>Spread</th></tr>${games.map(g=>`<tr><td>${g.round}</td><td>${g.opponentId?`<a class="player" href="player.html?event=${eventKey()}&id=${encodeURIComponent(g.opponentId)}">${esc(g.opponentName||g.opponentId)}</a>`:'Bye'}</td><td>${g.score??''}</td><td>${g.oppScore??''}</td><td>${esc(g.result||'')}</td><td>${g.spread==null?'':`${g.spread>=0?'+':''}${g.spread}`}</td></tr>`).join('')}</table></div></div><div class="panel"><h2>Head-to-Head</h2><div class="tablewrap"><table><tr><th>Opponent</th><th>Games</th><th>W</th><th>L</th><th>T</th><th>Spread</th></tr>${Object.values(h).map(x=>`<tr><td><a class="player" href="player.html?event=${eventKey()}&id=${encodeURIComponent(x.id)}">${esc(x.name)}</a></td><td>${x.games}</td><td>${x.w}</td><td>${x.l}</td><td>${x.t}</td><td>${x.spread>=0?'+':''}${x.spread}</td></tr>`).join('')}</table></div></div>`;const img=document.querySelector('#photo'),av=document.querySelector('#avatar');img.onerror=()=>{img.style.display='none';av.style.display='grid'}}